### ISSUE TITLE
Drone disconnects when loading file.

### ISSUE THREAD

**Issue by timower** [p-en-o-cw-2016/testbed-provided#1]
When running the testbed without any description file my autopilot can connect.
But when opening a description file two windows open and my autopilot can still connect until I press
run simulation, then I get the message: "Drone suddenly disconnected".
While my autopilot is still connected and is waiting for an image.

**Comment by jhoobergs** [comment]
He does indeed open 2 windows when you open a world from the initial filepicker. It works when you click cancel at the initial filepicker and then open the worldfile.

**Comment by samldd** [comment]
I made a new release which should resolve the issues. Can you test if it works now?

**Comment by timower** [comment]
Jep, now it works and does send data.
