### ISSUE TITLE
Error: World::tick()

### ISSUE THREAD

**Issue by Nickelium** [p-en-o-cw-2016/testbed-provided#11]
Error:World::tick() appears at certain times when running the provided testbed.
Whenever the error appears 5 times the whole testbed freezes and stops responding.

**Comment by samldd** [comment]
Is this an issue of the latest release, or have you had this issue also with the previous releases?

**Comment by th0rgall** [comment]
I believe we have the same issue.
To reproduce:
1. Start the provided testbed (v. 0.0.5), not loading a world (so, "Cancel" on the world loader).
2. Start the simulation or not, it doesn't matter.
3. Initiate a drone via the wire protocol externally. Now the testbed blocks after a while with the following output in the command line:
```
LOG: serverstub listning to new incoming connections
LOG: New drone connected to simulator
Error: World::tick()
Error: World::tick()
Error: World::tick()
Error: World::tick()
Error: World::tick()
```

**Comment by AntoonDeCleen** [comment]
If a worldfile is loaded originally, this problem does not seem to appear.

**Comment by samldd** [comment]
Thank you for the feedback. I think I know what the issue is! I will try to upload a new version this evening.

**Comment by Nickelium** [comment]
The problem doesn't seem to occur on V0.0.4. But in our case, it did appear when loading a worldfile (V0.0.5).

**Comment by samldd** [comment]
Can you test whether the issues are solved for you now in the new release?

**Comment by AntoonDeCleen** [comment]
The problem does not seem to occur anymore, I can now add a drone with or without a worldfile without problems.
