### ISSUE TITLE
Testbed doesn't send any data at a timestep

### ISSUE THREAD

**Issue by jhoobergs** [p-en-o-cw-2016/testbed-provided#2]
Our autopilot can connect to the testbed and gets all the initial data, but after our first write to the testbed, the testbed doesn't send any data anymore. I have tested it with the start simulation button and with the step simulation, but he doesn't send any data.

**Comment by samldd** [comment]
Can you test whether the new release also fixes this issue? Is your autopilot still connected with the testbed when this occurs?
