### ISSUE TITLE
Testbed reports wrong heading.

### ISSUE THREAD

**Issue by timower** [p-en-o-cw-2016/testbed-provided#4]
The heading reported by the testbed is always positive between 0 and 180 degrees.
I haven't tested the roll and pitch yet but out drone works when not changing yaw
so I assume they are correct.

**Comment by samldd** [comment]
I'm not sure what the issue is here? What do you mean with heading? Can you please give some more information so we can replicate your problem?

**Comment by timower** [comment]
The heading (yaw) in degrees that the testbed sends to the autopilot should be within -180 and 180 degrees yet when we configure our autopilot to rotate with a constant yaw rate, the Heading as defined by the wire protocol, send to our autopilot by your testbed is always positive.

**Comment by samldd** [comment]
Can you do another test to see whether it fulfills the specifications now? It should report values between the specified bouderies now.

**Comment by timower** [comment]
The values are in the right range, but the angle is measured from the negative X axis.
In the specification, the heading is measured between the positive X axis: 
>  (the angle, in degrees, between the cross product of
        the direction of view and positive Y, and positive X).

**Comment by samldd** [comment]
The release has been updated

**Comment by timower** [comment]
The drone still reports the wrong angle, zero should be facing left, while currently your testbed reports zero to be facing right of the starting position.

**Comment by samldd** [comment]
![image](https://cloud.githubusercontent.com/assets/4008980/23848140/139b6872-07d6-11e7-95e4-5e94cd3a7290.png)

Zo wordt het momenteel berekend. Rood is de richting waarin de drone kijkt en hij start op 90. Ik ben niet volledig mee met links en rechts. Maar zou het zo niet moeten kloppen?

**Comment by timower** [comment]
De foto is juist, maar wat het testbed doorstuurt in release 0.03 is fout, dan is de Z-as omgedraaid.
![2017-03-13-102332_2560x1440_scrot](https://cloud.githubusercontent.com/assets/5690698/23848652/8746cf62-07d8-11e7-963b-0ee89c984162.png)

Zoals te zien op de foto, drone kijkt naar Z-as, testbed zegt dat heading 0° is.

**Comment by samldd** [comment]
Oke, ik heb er gewoon een nieuwe release van gemaakt, want bij mij was het zoals op die afbeelding. Ik vermoed dat ik een foute file in de vorige release heb gezet. Ik hoop dat het nu in orden is! :)

**Comment by timower** [comment]
jep, nu is het in orde.

**Comment by samldd** [comment]
Oke. Bedankt voor de feedback!
