### ISSUE TITLE
World files not loaded correctly

### ISSUE THREAD

**Issue by KristofAchten** [p-en-o-cw-2016/testbed-provided#7]
World files are seemingly loaded incorrectly. Some faces are missing, some are spaced apart while they should be connected. A zip file with example world files has been included [Exported worlds.zip](https://github.com/p-en-o-cw-2016/testbed-provided/files/842213/Exported.worlds.zip). We initially weren't sure if it wasn't our code exporting wrong, but apparently other teams had this issue as well. That's why the assistant asked us to make this issue.

**Comment by jdeflander** [comment]
Have you made sure every face is defined clockwise? The testbed will not render faces from behind.

**Comment by KristofAchten** [comment]
Actually no, apparently we missed that in the specification. I'll fix the code and report back.

**Comment by KristofAchten** [comment]
This was indeed the case. Sorry, missed that specification!
