### ISSUE TITLE
The near plane is to close.

### ISSUE THREAD

**Issue by timower** [p-en-o-cw-2016/testbed-provided#8]
When our drone is trying to scan the objects in the world, the objects disappear when the drone gets closer than about 2 meters.

**Comment by samldd** [comment]
Is this also the case when you do this with the spectator in the testbed itself? Cause it should have the same camera setting as the drone and the spectator can get upon 0.05m of an object.

**Comment by timower** [comment]
No, as a spectator I can move close, but in the drone image the objects disappear at about 1-2meters.
